# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180329_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.CharField(default=False, max_length=10, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
    ]
