# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180327_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth',
            new_name='birthday',
        ),
    ]
